# Generated by Django 4.2.4 on 2023-08-30 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_message_deleted_message_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
    ]
