# Generated by Django 4.2.4 on 2023-09-04 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0007_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='thread_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
