# Generated by Django 4.2.4 on 2023-08-15 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_week_userweeks'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Marks', models.IntegerField(blank=True, null=True)),
                ('advisor', models.CharField(blank=True, max_length=250, null=True)),
                ('reviewer', models.CharField(blank=True, max_length=250, null=True)),
                ('conducted_on', models.DateField(blank=True, null=True)),
                ('audio_task', models.BooleanField(default=False)),
                ('description', models.BooleanField(default=False)),
                ('typing', models.BooleanField(default=False)),
                ('seminar_presentation', models.BooleanField(default=False)),
                ('feedback', models.BooleanField(default=False)),
                ('progress', models.BooleanField(default=False)),
                ('pending_topics', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='week',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserWeeks',
        ),
        migrations.AddField(
            model_name='weekdetails',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.week'),
        ),
    ]
