# Generated by Django 4.2.4 on 2023-08-15 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_weekdetails_week_user_delete_userweeks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
