# Generated by Django 4.2.4 on 2023-08-18 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_timeslot_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_week',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='review_in',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
