# Generated by Django 4.2.4 on 2023-08-18 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_current_week_user_review_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='current_week',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='review_in',
            field=models.IntegerField(blank=True, default=7),
        ),
    ]
