# Generated by Django 4.2.4 on 2023-08-19 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_booking_advisor_username_booking_intern_batch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='review_scheduled',
            field=models.BooleanField(default=False),
        ),
    ]
