# Generated by Django 4.2.4 on 2023-08-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_user_review_scheduled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='week',
            name='color',
        ),
        migrations.AddField(
            model_name='week',
            name='Schedule_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='week',
            name='day_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
