# Generated by Django 4.2.4 on 2023-08-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_rename_schedule_date_week_scheduled_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='week',
            name='day_name',
        ),
        migrations.RemoveField(
            model_name='week',
            name='scheduled_date',
        ),
        migrations.AddField(
            model_name='weekdetails',
            name='day_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='weekdetails',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
