# Generated by Django 4.2.4 on 2023-08-22 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_remove_week_day_name_remove_week_scheduled_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='domain',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
