# Generated by Django 4.2.4 on 2023-08-24 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_user_father_name_user_mother_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekdetails',
            name='pending_topics',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
