# Generated by Django 4.2.4 on 2023-08-26 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_weekdetails_pending_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekdetails',
            name='miscellenous_tasks',
            field=models.FileField(blank=True, null=True, upload_to='miscellenous_task'),
        ),
        migrations.AddField(
            model_name='weekdetails',
            name='personal_tasks',
            field=models.FileField(blank=True, null=True, upload_to='personal_task'),
        ),
        migrations.AddField(
            model_name='weekdetails',
            name='technical_tasks',
            field=models.FileField(blank=True, null=True, upload_to='technical_tasks'),
        ),
        migrations.AddField(
            model_name='weekdetails',
            name='this_weeks_tasks',
            field=models.FileField(blank=True, null=True, upload_to='weekly_task'),
        ),
    ]
